# Generated by Django 3.2.13 on 2022-06-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(default='', max_length=20)),
                ('price', models.CharField(default='0', max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
