# Generated by Django 3.2.13 on 2022-06-23 08:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220623_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.AddField(
            model_name='data',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
    ]
